user_input = input("Enter a list:")
input_list = user_input.split()
numbers = list(map(int, input_list))
total = sum(numbers)
length = len (numbers)
sorted1= sorted(numbers)
print(f"Orignal list of numbers:{numbers}")
print(f"Sum of numbers:{total}")
print(f"Number of elements:{length}")
print(f"Sorted list of numbers:{sorted1}")
print("Code executed by Prabhjot Kaur ERP:0221BCA047")
